version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17  # Change this based on your Java version (corretto11, corretto8, etc.)
    commands:
      - echo "Installing dependencies..."
      - mvn clean install -DskipTests

  build:
    commands:
      - echo "Building the project..."
      - mvn package -DskipTests

  post_build:
    commands:
      - echo "Build completed!"
      - ls -l target/

artifacts:
  files:
    - target/*.jar
  discard-paths: yes
